version: '3.8'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/project/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_USER=my_proj
      - POSTGRES_PASSWORD=my_proj
      - POSTGRES_DB=my_proj

  minio:
    image: minio/minio
    command: server /data
    restart: always
    ports:
      - "0.0.0.0:9000:9000"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_some_pass
    volumes:
      - ./data/minio/data:/data
      - ./data/minio/config:/root/.minio

volumes:
  postgres_data:
  project: