version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: some_pass
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    restart: always
    ports:
      - "0.0.0.0:9000:9000"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_some_pass
    volumes:
      - ./data/minio/data:/data
      - ./data/minio/config:/root/.minio